languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Home"
copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2006-01-02"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[author]
  name = "Rokia Biko"
  image = "img/rokia-biko.jpeg"
  headline = "Lorem ipsum dolor sit amet."
  #bio = "A little bit about you"
  links = [
     { email = "mailto:rokia@fastmail.com" },
     { github = "https://github.com/rokiabiko" },
     { instagram = "https://instagram.com/rokiabiko" },
     { reddit = "https://reddit.com/user/rokiabiko" },
     { x-twitter = "https://twitter.com/rokiabiko" },
  ]
